name: "FibBot"
description: "A GitHub Action that calculates Fibonacci numbers for numbers in PR content."

inputs:
  github_token:
    description: "GitHub token to authenticate API requests"
    required: true
  pr_number:
    description: "Pull request number"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PR_NUMBER: ${{ inputs.pr_number }}
