name: "FibBot"
description: "Scans Pull_request content for numbers, calculates their Fibonacci numbers, and posts a comment."
author: "Nkwenti"

inputs:
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)"
    required: false
    default: "true"
  max_threshold:
    description: "Max threshold for Fibonacci calculation"
    required: false
    default: "100"

runs:
  using: "composite"
  steps:
    - name: Build FibBot
      shell: bash
      run: cargo build --release
      
    - name: Run FibBot
      shell: bash
      run: ./target/release/fibbot
