name: "FibBot"
description: "Scans Pull Request content for numbers, calculates their Fibonacci numbers, and posts a comment."
author: "Nkwenti"

inputs:
  version:
    description: "The version of fibbot to use"
    required: true
  pr_number:
    description: "The number of the pull request"
    required: true
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)"
    required: false
    default: "true"
  max_threshold:
    description: "Max threshold for Fibonacci calculation"
    required: false
    default: "100"
  github_token:
    description: "GitHub token to interact with GitHub API"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build FibBot
      run: curl -o fibbot https://github.com/Nkwenti-Severian-Ndongtsop/Fibonacci-bot/releases/download/v${{ inputs.version }}/fibbot
      shell: bash

    - name: Run FibBot
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        export GITHUB_TOKEN="${{ inputs.github_token }}"
        fibbot "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}"
      shell: bash
