name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions: write-all
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --verbose
      - name: Move
        run: mv ./target/release/fibbot fibbot
      - name: Check
        run: ls -la fibbot
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fibbot-bin
          path: fibbot

  release:
    name: Release
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Check
        run: ls
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: '**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}